[WIP][12.0][ADD] base_phone_rate_import_bandwith
OCA/vertical-isp pull request #44
Opened 2019-11-11 13:37 UTC by murtuzasaleh

WIP

2019-11-11 15:34 UTC, murtuzasaleh commented
@dreispt

2019-11-11 16:46 UTC, dreispt commented on base_phone_rate_import_bandwith/README.rst
> +You are welcome to contribute. To learn how please visit https://odoo-community.org/page/Contribute.
It's easier to use the `readme` fragments subdirectory, and put here a README placeholder file.

2019-11-11 16:56 UTC, dreispt commented on base_phone_rate_import_bandwith/readme/CONFIGURE.rst
> +This module needs no additional configuration post installation
Remember to add USAGE.rst - it is required.

2019-11-11 16:56 UTC, dreispt commented on base_phone_rate_import_bandwith/wizard/base_phone_rate_import.py
> +            wb = open_workbook(temp_path + '/xsl_file.xlsx')
You should be able, without having to write it to a temp disk file.
Not 100% sure if xlrd supports that, though.

2019-11-11 16:56 UTC, dreispt commented on base_phone_rate_import_bandwith/wizard/base_phone_rate_import.py
> +            for values in data_list:
Not a problem, but I would have used a single loop over the lines...

2019-11-11 16:56 UTC, dreispt commented on base_phone_rate_import_bandwith/wizard/base_phone_rate_import.py
> +                country_rec = res_country_obj.search([('name', '=',
More robust if you ignore letter case:
```suggestion
                country_rec = res_country_obj.search([('name', '=ilike',
```

2019-11-12 10:25 UTC, dreispt commented on base_phone_rate_import_bandwith/wizard/base_phone_rate_import.py
> +                                               'rate': bandwith_data[2]})
You must update an existing rate if the dial prefix already exists.

2019-11-14 10:23 UTC, murtuzasaleh commented
@dreispt @max3903 Can you please review this PR.

2019-11-22 09:59 UTC, dreispt commented
Ping @kvedder-amplex

2019-11-22 10:58 UTC, dreispt requested changes

2019-11-22 10:58 UTC, dreispt commented on base_phone_rate_import_bandwith/wizard/base_phone_rate_import.py
> +            fname = temp_path + '/xsl_file.xlsx'
Nitpick: user `os.path.join`

2019-11-22 10:58 UTC, dreispt commented on base_phone_rate_import_bandwith/wizard/base_phone_rate_import.py
> +            fp = open(fname, 'wb+')
I would rather prefer to use an in memory IOStream, but I won't pick on this.

2019-11-22 10:58 UTC, dreispt commented on base_phone_rate_import_bandwith/wizard/base_phone_rate_import.py
> +                    if rownum > 0:
This `if` is not necessary if you use `range(1, ...)`

2019-11-22 10:58 UTC, dreispt commented on base_phone_rate_import_bandwith/wizard/base_phone_rate_import.py
> +                            [('dial_prefix', '=', bandwith_data[1])])
`bandwith_data[1]` returns a float and we get a zero decimal when it is forced as a char: `92.0`
We don't want that, and need a proper conversion, to get `92` instead.
This needs fixing.

2019-11-22 10:58 UTC, dreispt commented on base_phone_rate_import_bandwith/wizard/base_phone_rate_import.py
> +            os.remove(fname)
:+1:

2019-11-22 15:23 UTC, dreispt commented
Superseded by #45 Thank you @murtuzasaleh

2019-11-22 15:23 UTC, closed without merging